# Generated by Django 3.2 on 2021-04-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('org_page', models.URLField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_modified', models.DateField(auto_now=True)),
            ],
        ),
    ]
