# Generated by Django 3.2 on 2021-05-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_organization_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='contact_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
