# Generated by Django 3.2 on 2021-05-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_exclusion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exclusion',
            name='text',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
